
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.jocker.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
      table-underline: true
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3600/xxx?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8000
